[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "textools"
dynamic = ["version"]
authors = [
  {name = "Ostpopcorn"}
]
requires-python = ">=3.8"
description = "Tools for working with LaTeX files"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["latex", "tex", "comments", "arxiv"]
classifiers = [
	"License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3 :: Only",
	"Topic :: Text Processing :: Markup :: LaTeX"
]
dependencies = []

[project.optional-dependencies]
test = [
  "pytest"
]

[project.urls]
Repository = "https://github.com/Ostpopcorn/tex-tools.git"

[tool.setuptools]
packages = ["textools"]

[tool.setuptools.dynamic]
version = {attr = "textools.__version__"}

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
